### ISSUE TITLE
3.2.3 Keep-Alive repeat the control packets structure

### ISSUE THREAD

**Issue by quink-black** [Haivision/srt-rfc#105]
![image](https://user-images.githubusercontent.com/9263126/130387456-85739353-c5b1-465d-b99f-3775e913e316.png)

It makes me confused why the control packet structure is showed again at the keep-alive section. It's more simple to say that keep-alive packet is one of the control packets without control information field.

**Comment by quink-black** [comment]
OK, Handshake packet only shows the CIF, other packet types following the style of keep-alive.

**Comment by maxsharabayko** [comment]
Hi @quink-black 
We actually started with the way you propose "saying that keep-alive packet is one of the control packets without control information field". However, it was a bit inconvenient to navigate through the RFC back and forth to find the syntax of the control information field. So to make life easier, we are just copying the whole SRT packet structure. This is not a good approach, but save a couple of seconds each time you want to refresh the structure of a certain packet 🙂
