### ISSUE TITLE
Destination socket ID in the caller conclusion packet

### ISSUE THREAD

**Issue by sthilden** [Haivision/srt-rfc#120]
I have a question regarding the destination socket ID in the caller conclusion handshake packet.

In section 4.3.1.2 ("The Conclusion Phase"), it says for the conclusion packet sent by the caller; "The Destination Socket ID in this message is the socket ID that was previously received in the induction phase in the SRT Socket ID field of the handshake structure."

However, testing the open source SRT library (https://github.com/Haivision/srt), I observe the following behavior;
- The listener does not insert its own ID in the "SRT socket ID" field of the induction reply (as this specification says it should), but instead inserts the socket ID of the caller.
- The caller always sets 0 as the "destination socket ID" in the conclusion packet it sends, and not the socket ID previously received from the listener in the induction phase.
- If a caller is implemented to use the socket ID previously received from the listener as the destination Socket ID in the conclusion packet, then the listener will not respond at all, and the handshake will not succeed.

Thus, if an SRT caller is implemented following the current specification, it will not be compatible with the open source SRT library listener, which is unfortunate.

I therefore wonder if the specification instead should state that the destination socket ID should be set to 0 in the conclusion packet sent by the caller?

**Comment by maxsharabayko** [comment]
In the induction phase, the listener is not creating any SRT socket, therefore there is no socket ID to send.
The listener can only reply with "0" in the Source SRT Socket ID.
The SRT socket is only created on the listener side after receiving the Conclusion Request from the caller.

The description of the handshake procedure is relatively poor. PR 116 suggests some rework, but the PR itself is still a work in progress.

**Comment by sthilden** [comment]
Thank you for the reply!

I see also the destination socket ID for the caller conclusion packet is 0 in the updates of PR #116.

I will close this issue then, as this the described issue is covered by by PR #116.
