### ISSUE TITLE
unresolved issue by #33

### ISSUE THREAD

**Issue by justinjoy** [Haivision/srt-rfc#34]
- [x] Author's organization (https://github.com/Haivision/srt-rfc/blame/master/draft-sharabayko-mops-srt.md#L29): different?
 - [x] Reference for specific numbers (https://github.com/Haivision/srt-rfc/blame/master/draft-sharabayko-mops-srt.md#L157): is there any reference such as a conference paper?

**Comment by maxsharabayko** [comment]
1. Jean is employed by Haivision (Canada), while we are by the German branch.
2. The second link now points to a different place. Was it regarding UDT?

**Comment by justinjoy** [comment]
> 2. The second link now points to a different place. Was it regarding UDT?

that's my mistake. It's not L104, it's about L157. I fixed the link.

>This move increased the end-to-end 
latency of live streaming to over 30 seconds, which makes it unattractive for many 
use cases. Over time, the industry optimized these delivery methods, bringing the 
latency down to 3 seconds.

**Comment by maxsharabayko** [comment]
Ok, I see. Unsupported numbers, taken from the head. It is bad, but let it be so.

**Comment by mbakholdina** [comment]
I've corrected Jean's organization to the right one in the current version, but we have different organizations.
