### ISSUE TITLE
Replace the security consideration section

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt-rfc#64]
Joonwoong investigated about security consideration section (there exists RFC for it), but the requirement is too broad and it is too much to consider the whole security aspects of SRT (including attacker models…) for now.
Therefore, we try with this concise version and will have to revisit if the reviewer is not happy with it later.

**Suggested text:**

SRT provides confidentiality of user data using stream ciphers as specified in {{Encryption}}, which is the only improvement of security upon UDP. That means other limitations from UDT remain as they are, and it needs to consider any security protection mechanisms at a upper layer depending its security requirements. Integrity protection of user data can also be supported as described in {{###Ciphers (AES-CTR)}}, and its usage details are out of scope for the present document.
 
The encryption feature of SRT requires some cautions. SEK needs to be changed with an appropriate refresh period, to avoid any issues which might be occurred by the use of long lived security keys. The shared secret for KEK generation needs to be carefully configured by a security officer, who is supposed to set security policies to force encryption and limit key size selection. Another aspects to consider is caching of KMmsg. When encryption and decryption of the same messages affects processing cost for sender or receiver, cached KMmsg could be retransmitted or checked before deciphering.

**Comment by maxsharabayko** [comment]
TODO: remove reference to UDT ("That means other limitations from UDT remain as they are...").

**Comment by mbakholdina** [comment]
@maxsharabayko I've taken a look and it seems to be you are the best person to review this part. Could you please make your corrections, I'll update the section and then we will wait for possible notes or corrections from reviewer as Joonwoong is suggesting and make corrections.

**Comment by mbakholdina** [comment]
@maxsharabayko Reassigning to you.
